---
name: Dockerfile Scan

on:
  workflow_dispatch:

jobs:
  dockerfile_scan:
    runs: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: scan dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
